language:
  - swift
os: osx
osx_image: xcode12.4
script:
  - xcodebuild -scheme DictionaryEncoder -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)

