language:
  - swift
osx_image: xcode12.4
script:
  - xcodebuild -scheme DictionaryEncoder -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)

